[package]
name = "verifront"
version = "0.1.0"
authors = ["akitsu-sanae <akitsu.sanae@gmail.com>"]
edition = "2018"

[dependencies]
sexp = "1.1.4"
tempfile = "3.0.7"
lazy_static = "1.3.0"
num-bigint = "0.2"
num-traits = "0.2.8"
